### ISSUE TITLE
HICOPS execution on Intel Xeon gold crashes with a segmentation fault

### ISSUE THREAD

**Issue by ksumesh93** [hicops/hicops#4]
The issue can be reproduced by using these search parameters
![Capture](https://user-images.githubusercontent.com/25102653/154621849-257ea9fc-487e-4843-83e7-1cf321f0935a.PNG)

Search parameters used:
Min peptide length=6
Max Peptide length=40

Modifications: 
mod1=M 15.99 4
mod2=S 79.966331 4
mod3=T 79.966331 4
mod4=Y 79.966331 4
mod5=C 57.0215 4

Experimental spectra dataset:
PXD000612

**Comment by mhaseeb123** [comment]
The problem is being caused by memory exhaustion on the system. Please either reduce the index size to fit inside ~70% of the available RAM or use multi-node machine and MPI.

**Comment by mhaseeb123** [comment]
This functionality is intentional as HiCOPS supports only in-core computing and is able to effectively pool in memory resources from several nodes when needed.
